parameters:
    database_driver: pdo_pgsql
    database_host: 127.0.0.1
    database_port: '5432'
    database_name: symfonytest
    database_user: postgres
    database_password: root
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: c7b31ba70b09b1720c31c3d9d03eb02999c9019f
    database_path: null
